# docker-compose.postgres.yml
services:
  omop-postgres:
    image: postgres:16
    container_name: omop_postgres
    environment:
      POSTGRES_USER: omop
      POSTGRES_PASSWORD: omop
      POSTGRES_DB: omop
    ports:
      - "5432:5432"
    volumes:
      - omop_data:/var/lib/postgresql/data
      - ./sql/omop_schema_setup.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
volumes:
  omop_data:
